# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://danielpadgett.net
title: Daniel Padgett
email: danpadgett01@gmail.com
author: Daniel Padgett
description: 'Dan Padgett is a user-experience designer who turns insight into innovation. He applies creative and critical thinking to create user-centered solutions and products for the problems and challenges you face.'
copyright: 'Copyright &copy; 2019 Daniel Padgett. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

#social:
 # - title: Academia
 #   url: https://tinyurl.academia.edu/DanielPadgett
#  - title: PhilPapers
 #   url: http://philpapers.org/profile/92468
    
  
